/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:c1b60db7-6112-45d3-a153-5c563863d191",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_coO9fEtIn",
    "aws_user_pools_web_client_id": "3d6fbfvp9ec28hvu4n62hpa28n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://33j7byixzjakjj7goeflqd22ca.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vbsjariyh5gstmquee7xbyo6ei"
};


export default awsmobile;
