/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a8ed029b-664c-4e26-9d53-567aa554f3f9",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Ny6k3Rq2j",
    "aws_user_pools_web_client_id": "1b648lbuj00ljr1ibouvnl97s1",
    "oauth": {}
};


export default awsmobile;
